### ISSUE TITLE
Fabric API key still required.

### ISSUE THREAD

**Issue by MatrosSkin** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#9]
## Expected Behavior
I should be able to build a simple android app with Firebase Crashlytics.

## Actual Behavior
Error during building the app:
```
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.
```
[full-build.log](https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/files/1951801/full-build.log)

## Steps to Reproduce the Problem
Here is example app https://github.com/Matrosskin/crashtest, just try to build it with command `npm run cordova -- build`.

## Specifications

  - Plugin version: 0.0.6
  - Framework: Cordova
  - Framework version: 8.0.0
  - Operating system: Ubuntu 16.10

**Comment by ReallySmallSoftware** [comment]
I believe I have seen this before. I think there is a clash with the cordova-plugin-firebase plugin. I am still trying to get to the bottom of this - I don't use cordova-plugin-firebase and don't get that problem.

I'm not attempting to apportion blame to that plugin - just reporting the experience I've had.

**Comment by MatrosSkin** [comment]
@ReallySmallSoftware thank you for the answer. I also saw once topic where guys assume that the problem with firebase-auth which was in their gradle dependencies (sorry, I can't find again the page, it was somewhere on StackOverflow). I tried to exclude that dependency and API key still required, but I am not sure if I did it properly for 100%.

For me, it is fine at the moment to use Fabric service so I will not wait and search further for the solution in nearest time. I assume I should not close the issue as it is not really solved at the moment, am I right?

**Comment by ReallySmallSoftware** [comment]
Yes, leave it open and I'll try and get to the bottom of it. Thanks.

**Comment by MatrosSkin** [comment]
The problem was caused by firebase-crash which was installed by cordova-plugin-firebase.
So the problem was solved in my case by using plugins which contain only really used dependencies: phonegap-plugin-push, cordova-plugin-firebase-analytics and your plugin.
Closing the issue.

**Comment by YoavHortman** [comment]
This issue is still occurring and I can not remove cordova-firebase-plugin.
Please reopen.

**Comment by MatrosSkin** [comment]
@YoavHortman I think it is not a problem of cordova-plugin-firebase-crashlytics because you try to use two components for reporting about crashes: new one firebase crashlytics and old one firebase crash. To solve the issue you should be able to install only one of them. I am quite confident that it is possible to find each firebase feature as separate plugins (as I did to solve issue in my project). Otherwise, you need to cut off the firebase crash from cordova-plugin-firebase somehow.

**Comment by piotr-cz** [comment]
For me the problem is that Firebase Crashlytics requires `com.google.gms.google-services` plugin to read API key from google-services.json file (see this [SO](https://stackoverflow.com/a/55007994/1012616) answer).

Installing [cordova-support-google-services](https://www.npmjs.com/package/cordova-support-google-services) fixed the issue.

I have no idea why Google Services Gradle Plugin defined in this plugins [grade file](https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/blob/0.0.8/firebase-crashlytics.gradle#L12) doesn't work

**Comment by MatrosSkin** [comment]
@piotr-cz Do you have any other Firebase plugins in your project?

**Comment by piotr-cz** [comment]
No, this is the only one.

My cordova related dependencies are:

```json
    "cordova-android": "^8.0.0",
    "cordova-ios": "^5.0.0",
    "cordova-plugin-firebase-crashlytics": "0.0.8",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-request-location-accuracy": "^2.2.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
```

I've also tried to add `google()` and increment `com.google.gms:google-services` version to 4.2.0 in `dev-firebase-crashlytics.gradle` as in
- [cordova-support-google-services/build.gradle](https://github.com/chemerisuk/cordova-support-google-services/blob/v1.3.1/build.gradle) 
- https://github.com/arnesson/cordova-plugin-firebase/pull/1028
- https://github.com/arnesson/cordova-plugin-firebase/pull/1011

but that didn't help.
